# Generated by Django 3.1.5 on 2021-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name': 'Biography'},
        ),
        migrations.AddField(
            model_name='biography',
            name='author_name',
            field=models.CharField(default='Artashes Ghahriyan', max_length=55),
            preserve_default=False,
        ),
    ]
